### ISSUE TITLE
Strange resolution issues on macOS

### ISSUE THREAD

**Issue by Dooskington** [tomaka/glutin#1025]
Hi, I've been having issues working with glutin on macOS recently.

I am trying to create a 256x256 window. However, after doing this, I get back a window with inner_size 512x468 and outer_size 512x512. I am assuming the sizes are doubled due to hidpi/retina stuff (I am on a macbook pro), but the real issue is the inner size - why is it 468 instead of 512? The title bar is taking up part of the 256x256 rect that I specified.

I also believe that this is causing my OpenGL viewport to be messed up. A 32x32 pixel square is now being shown as slightly rectangular - because the inner size of the window is incorrect, so the gl viewport gets messed up upon context creation (I think).

Here's the code in question:

```
        let window = glutin::WindowBuilder::new()
            .with_title("Window")
            .with_dimensions(256, 256)
            .with_min_dimensions(256, 256)
            .with_max_dimensions(256, 256);

        let context = glutin::ContextBuilder::new()
            .with_vsync(true);

        let events_loop = glutin::EventsLoop::new();
        let gl_window = glutin::GlWindow::new(window, context, &events_loop).unwrap();

```
Can somebody clarify what is going on? I think `with_dimensions` should be specifying the inner size of the window, not the outer size.

**Comment by francesca64** [comment]
Do things work better using tomaka/winit#548? That PR also fixes max/min dimensions on macOS, since before that they constrained the window size *including* the title bar.

**Comment by Dooskington** [comment]
@francesca64 How would I try that? Do I need to rebuild glutin with your WIP branch as the source for it's winit dependency?

I just tried again after removing the min and max dimension calls, and now I'm getting the expected behavior, so I guess they were the culprits.

If your PR has fixes for that, as well as fixes for the DPI stuff, I will be eagerly waiting for it to be merged 😄

**Comment by francesca64** [comment]
Since there are some breaking changes, it would be easier to use the pre-patched glutin branch: https://github.com/francesca64/glutin/tree/super-dpi

I also didn't document the new API yet, so...

```rust
let window = glutin::WindowBuilder::new()
    .with_title("Window")
    .with_dimensions(glutin::LogicalSize::new(256.0, 256.0))
    .with_min_dimensions(glutin::LogicalSize::new(256.0, 256.0))
    .with_max_dimensions(glutin::LogicalSize::new(256.0, 256.0));

let context = glutin::ContextBuilder::new()
    .with_vsync(true);

let events_loop = glutin::EventsLoop::new();
let gl_window = glutin::GlWindow::new(window, context, &events_loop).unwrap();
```

(you could actually just use `(256, 256).into()`)

Then for rendering, you'd use `LogicalSize::to_physical(&self, dpi_factor: f64) -> PhysicalSize` to get the physical pixels (DPI factor being acquired from `Window::get_hidpi_factor`), and either access the `width` and `height` members (both `f64`) or use the `Into<(f64, f64)>` and `Into<(u32, u32)>` conversions (the latter of which automatically rounds). `GlWindow::resize` will be changed to take `PhysicalSize`, but at the moment you have to remember that's what it needs yourself. All window functions both produce and consume either `LogicalSize` or `LogicalPosition`, whereas monitor and context functions produce and consume either `PhysicalSize` or `PhysicalPosition`.

This will be merged quite soon; I just need to 1) document it, and 2) release 0.15.1 first. Also, since you seem to be trying to make the window un-resizable, you'll soon be able to use the upcoming `with_resizable` method: tomaka/winit#540
