### ISSUE TITLE
`WindowBuilder`s function `with_resizable` is not mentioned in the glutin documentation

### ISSUE THREAD

**Issue by Rijenkii** [tomaka/glutin#1032]
Function `with_resizable` is not mentioned in the [glutin documentation](https://docs.rs/glutin/0.16.0/glutin/struct.WindowBuilder.html)

**Comment by francesca64** [comment]
That's because I never made a glutin release for winit 0.15.1, so the docs were never rebuilt (today I've learned a lesson about the cost of being a bit loose on semver). winit 0.16.0 will most likely be released *extremely* soon, so the corresponding glutin release for that will include everything.

**Comment by francesca64** [comment]
Ta-da: https://docs.rs/glutin/0.17.0/glutin/struct.WindowBuilder.html#method.with_resizable
