### ISSUE TITLE
Titlebar looks weird under wayland

### ISSUE THREAD

**Issue by binomial0** [tomaka/glutin#1044]
When I run the "window" example under Wayland, the window decorations are looking very unusual:
![glutin_wayland](https://user-images.githubusercontent.com/7315000/42471372-c0ea2428-83bd-11e8-9bc3-f56063484b5c.png)
When I use xorg instead, it all looks like expected:
![glutin_xorg](https://user-images.githubusercontent.com/7315000/42471423-eae7c140-83bd-11e8-9c40-b376be554546.png)

This affects several downstream projects, including alacritty and Servo.

System information:
Ubuntu 18.04 64bit, Gnome 3.28.1, Display driver: radeon

**Comment by francesca64** [comment]
This is an upstream issue that isn't directly related to glutin or winit: Smithay/wayland-window#19

Since Wayland requires clients to draw their own decorations, getting native results would require non-trivial time investment. I'd be interested in trying to design a better set of stock decorations, but I'd likely make them pink.

**Comment by binomial0** [comment]
Thank you! I didn't know that.
Shipping your own set of decorations seems a bit out of scope for this project, but if there's no other option...
&lt;mini-rant&gt; I don't understand why Wayland requires you to do that, though. Window decorations seem like some basic functionality... but then again, I'm quite a noob regarding all this, so what do I know... &lt;/mini-rant&gt;
Anyway, closing this, because the issue seems to be further upstream.

**Comment by vberger** [comment]
> I don't understand why Wayland requires you to do that, though. Window decorations seem like some basic functionality... 

To expand a little more on @francesca64 's explanations, decoration drawing is currently handled by [SCTK](https://github.com/smithay/client-toolkit) (wayland-window is its predecessor).

Wayland requires a client to be able to draw its own decorations, as some compositors will not draw them for the clients (on example is Gnome's mutter). As such, I have implemented in SCTK a very basic decoration drawing. It aims at being functional rather than pretty, as I am no GUI designed. Any help to make them prettier would be very welcome though.

On the other hand, since a few days ago, there is now a protocol extension to allow negotiation between the client and the server of which will draw the decorations (as for example, KDE's Kwin can handle the decorations drawing, and tends to prefer doing it). I plan to integrate this protocol is SCTK at some point, and have [an issue tracking it](https://github.com/Smithay/client-toolkit/issues/1) once I get the bandwidth for it (or someone else want to tackle it), and it'll also require other compositors to adopt this extension (hopefully KDE will switch to the standard one rather than its custom internal one).
