### ISSUE TITLE
OpenGL window creation forces glEnable(cap = GL_FRAMEBUFFER_SRGB)

### ISSUE THREAD

**Issue by norru** [tomaka/glutin#1065]
Hello,

I am trying to disable hardware sRGB conversion in framebuffer as I need to plug in my own color transform.

At the moment glutin/winit ignores both the fact that I'm explicitly requiring a simple `Rgba8` framebuffer

```rust
pub type ColorFormat = gfx::format::Rgba8;
```
and that I'm also **explicitly** requesting srgb to be disabled

```rust
let context_builder = glutin::ContextBuilder::new()
		.with_vsync(true)
		.with_srgb(false);
```

As a result this appears in the `apitrace` log during window creation, and sRGB transform is applied.

```
glEnable(cap = GL_FRAMEBUFFER_SRGB)
```

as a workaround, I successfully applied the following:

```rust
unsafe { gl::Disable(gl::FRAMEBUFFER_SRGB); }
```

which is, however, rather unnecessary/unsightly.

Ubuntu 17.10
glutin = "0.18"
rustc 1.30.0-nightly (cb6d2dfa8 2018-09-16)

**Comment by norru** [comment]
It's probably caused by `gfx-device-gl` during initialisation.

**Comment by msiglreith** [comment]
yes, we explicitly enable that on gfx-rs side, unrelated to glutin

**Comment by norru** [comment]
What's the correct workaround then? You seem to be ignoring the `.with_srgb(false)` flag and hardcoding sRGB - even if the Format encoding is `Unorm`.

**Comment by norru** [comment]
But yes, you're right, it does appear that it's a `gfx-device-gl` "feature" (ie a bug).

**Comment by msiglreith** [comment]
What the flag does is to convert colors from linear to srgb when drawing to the framebuffer (not only default) **if** the framebuffer is backed by sRGB targets.

We don't control that, nor do we actually have access to the flag `with_srgb` which is set on context creation. OpenGL ES doesn't even expose that GL_FRAMEBUFFER_SRGB flag as it's just set as the default behavior. The actual cause is that the driver doesn't create a framebuffer with the correct format.

The correct workaround is to render in a separate framebuffer/rendertarget and blit into the default framebuffer on present. At this point we probably have to enable/disable this flag to not affect the blit operation but that's not something we implemented so far.

**Comment by norru** [comment]
> if the framebuffer is backed by sRGB targets.

Yept, that's what I though - then the bug must be somewhere else - I am definitely *explicitly* requesting creation of the framebuffer target as R8_G8_B8_U8, Unorm (which shouldn't be detected as sRGB target)

**Comment by francesca64** [comment]
So, this isn't a problem with glutin?

**Comment by norru** [comment]
Possibly, but the setting in Glutin is misleading as it appears to have no effect whatsoever.

**Comment by norru** [comment]
I have solved the problem by adding a postprocessing shader afetr rendering onto an offscreen target, and explicitly applying the sRGB correction in the shader when needed.
