### ISSUE TITLE
Proposal: Conversion of VirtualKeyCode to string

### ISSUE THREAD

**Issue by ekse** [tomaka/glutin#1074]
Hi,

I would like to add conversions between VirtualKeyCode and &str. This is something we added to our project [1] to be able to serialize them to a file and that you previously suggested in issue #842. I decided to open an issue so we can agree on an implementation before I start working on it.

I would implement the Default (which automatically provides ToString) and FromStr traits on VirtualKeyCode. This can be done trivially using the strum crate (https://crates.io/crates/strum). Alternatively we can write the conversion manually for each variant at the cost of more boilerplate code. 

[1] https://gitlab.com/veloren/game/blob/master/voxygen/src/keybinds.rs#L82

Thanks,

Sébastien

**Comment by francesca64** [comment]
It's been a while since #842, and now this issue is relevant to [winit](https://github.com/tomaka/winit) instead of glutin. so should be discussed there instead.

I encourage you to weigh in on the discussion in tomaka/winit#652. tomaka/winit#304 is also relevant, though you'll likely get less attention there.

**Comment by ekse** [comment]
Closing as this is now implemented in winit.
