### ISSUE TITLE
Clarification in the docs on key codes

### ISSUE THREAD

**Issue by dylanede** [tomaka/glutin#259]
It would be nice to know exactly how glutin key codes map to native key codes. For example, are they mapping to physical keys, or are they dependent on the user's keyboard layout? Also, exposing a way to get the actual native key code would be handy for applications that must then pass on the native key code to another API (e.g. CEF). Otherwise the encoding implemented by glutin must be reversed by the application.

**Comment by Kasran** [comment]
I did some experimentation using the keyboard configuration options that Windows 10 provides. When using the Japanese IME in non-romaji modes (e.g. hiragana), the `Pressed` events all have no `VirtualKeyCode` associated with them, but the `Released` events have the ones you'd expect. Windows also provides a Dvorak keyboard layout, and the `VirtualKeyCode` field of the events changes accordingly - so my guess is that the `VirtualKeyCode` field is dependent on the keyboard layout.

However, the second field of the `KeyboardInput` event is a scan code, which is always the same for each key, regardless of layout: when I press the D key, the `VirtualKeyCode` reported is D in the regular layout and E in the Dvorak layout, but the scan code is 32 in both cases. This might be the native key code you're looking for.

You may know all this already, because this is an old issue, but I figured I'd break down what I found for future readers.

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/35
