### ISSUE TITLE
Scrolling speed is too slow

### ISSUE THREAD

**Issue by mdinger** [tomaka/glutin#420]
In https://github.com/servo/servo/issues/5660 they decided that glutin should be sending a more reasonable scrolling speed than it is doing. They shouldn't need to do post processing to fix it.

**Comment by tomaka** [comment]
Well, glutin just returns the number of wheel movements.
For example if you roll one "tick", it generates an event containing `1`.

**Comment by mdinger** [comment]
cc @pcwalton @jdm ^^

**Comment by pcwalton** [comment]
There isn't the idea of a "tick" for trackpad scrolling. You need a "number of pixels" abstraction.

**Comment by vberger** [comment]
As a comparison, Wayland provides sub-pixel precision scrolling with a trackpad, but the event generated by the compositor when using a mouse is a scroll of 10 pixels for each "tick".

Looks like it's x11 the problem here, as it's the only one measuring the scrolling in "ticks". Windows seems to provide an amplitude as well ( https://github.com/tomaka/glutin/blob/master/src/api/win32/callback.rs#L112-L121 ), so it might be relevant to normalize x11 on this.

**Comment by retep998** [comment]
Would this be fixed by the change in #405 of providing an `f64` instead of an `i32` so you can get precise scrolling when available?

**Comment by tomaka** [comment]
With #405 the value would still be `-1` or `1`. #405 is a bugfix for win32 more than anything else.

**Comment by robertknight** [comment]
PR for this - https://github.com/tomaka/glutin/pull/483

**Comment by robertknight** [comment]
PR #483 has been merged. This can be closed. Glutin now allows the platform to express scroll deltas either in pixels or lines/chunks/rows. When expressed in lines, it is up to the app to scroll a suitable amount. This is now done in Servo.

**Comment by mdinger** [comment]
Nice!
