### ISSUE TITLE
Consider adding a drag & drop event

### ISSUE THREAD

**Issue by thelink2012** [tomaka/glutin#496]
GLFW as of 3.1 provides a callback to queue dropped files and afaik SDL2 also has such event.

**Comment by mitchmindtree** [comment]
Just an update: It looks like this event [has been added](https://github.com/tomaka/glutin/blob/master/src/events.rs#L15), but is only implemented for the `win32` api so far.

**Comment by mitchmindtree** [comment]
I've been looking into how to get this working for cocoa.

In order to receive drag events, cocoa requires implementing the `NSDraggingDestination` protocol. It seems this involves subclassing `NSWindow` and then implementing the [`performDragOperation`](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Protocols/NSDraggingDestination_Protocol/#//apple_ref/occ/intfm/NSDraggingDestination/performDragOperation:) which gets called when a drag is released over the window. We could use this callback to add an event to the `VecDeque` of `pending_events`. I found a simple example of implementing the `NSDraggingDestination` protocol in obj c [here](http://stackoverflow.com/questions/8567348/accepting-dragged-files-on-a-cocoa-application).

Once implemented, we will have to register the window as a dragging destination for the specific types of files that we can want to handle (in our case, all of them). To do this, we have to call the [registerForDraggedTypes](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSWindow_Class/#//apple_ref/occ/instm/NSWindow/registerForDraggedTypes:) method on our window after we have created it and ensured that it is `non_nil`. This will probably look something like this:
```rust
// Register the window as a dragging destination for creating `DroppedFile` events.
msg_send![*window, registerForDraggedTypes:NSArray::arrayWithObject(nil, appkit::NSFilenamesPboardType)];
```

**Comment by mitchmindtree** [comment]
The cocoa API supports handling multiple dropped files at once. When this occurs, we could either:
- emit multiple `DroppedFile` events or
- change `DroppedFile(PathBuf)` to `DroppedFile(Vec<PathBuf>)`

The second option might be useful for applications that need to know when multiple files are dropped at once though would be a breaking change. The first option is probably simplest to implement in the meantime.

**Comment by thelink2012** [comment]
As a side note, Win32 also supports the event of many files at once (and that's what's used in my impl), however I still opted for triggering many events, seems less intrusive imo.

**Comment by retep998** [comment]
It is possible to support more advanced drag and drop, where the window receives notification of the thing being dragged onto it before it is dropped. This allows for visual feedback to be displayed to the user, such as displaying where the dropped thing will be inserted or whether dropping is allowed.

https://msdn.microsoft.com/en-us/library/windows/desktop/bb776905(v=vs.85).aspx

**Comment by retep998** [comment]
Also for the record the current Windows implementation only accepts paths that can fit in`[u16; winapi::MAX_PATH]`, which is actually rather small because `MAX_PATH` is only 255 while in reality paths can be up to 32767 big.

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/44
