### ISSUE TITLE
Support X11 systems that don't have extension libraries installed

### ISSUE THREAD

**Issue by tomaka** [tomaka/glutin#554]
libXcursor, libXxfvm86, libXi, etc. are not necessarly available everywhere.

**Comment by robertknight** [comment]
Any idea of what real-world systems this affects? Implementing a fallback for when XInput is not available is possible but you probably only want to have to maintain that code if there is a concrete use case for it.

**Comment by tomaka** [comment]
The reason why I opened this issue is because of my raspi.
Its xinput library is missing some symbols and cannot be loaded. I had to remove support for xinput in glutin to make it work.

**Comment by robertknight** [comment]
That's a pretty good use case. I don't have a raspi to hand at the moment, do you know what XInput symbols are missing? I presume they are not core functionality because I've seen blogs about [using XInput](http://pikiosk.tumblr.com/post/41042790814/capacitive-touchscreen-raspberry) with touchscreen devices.

**Comment by tomaka** [comment]
The error said that `XIBarrierReleasePointer` was missing. Perhaps there are others, but the error only reports the first one.

Also `Xcursor` wasn't installed by default either.

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/49
