### ISSUE TITLE
Feature: Get Cusor Position

### ISSUE THREAD

**Issue by RichardlL** [tomaka/glutin#753]
It appears there is no way to get the cursor position without iterating through all the mouse updates.  This could cause performance issues if only one update is required  per frame, and naively implemented

e.g.

```
match Event {
    MouseMoved(x, y) => {
        expensive(x,y);
    },
     _ => (),
}
```

Current fix 

```
let (mut x, mut y) = (0, 0);
match Event {
    MouseMoved(a, b) => {
        x = a; y = b;
    }
    _ => (),
}
expensive(x, y);
```

This could possibly be made an event iterator variant, maybe tacked on once as the first/last event, so only executed once per cycle.

Something like this for the iterator? (glfwGetCursorPos() is the glfw equivalent function call)

```
impl newCurrentPosition {
    fn newCurrentPosition(_) => Option<newCurrentPosition> {
        if get_cusor_pos() != last_current_pos {
            Some(newCurrentPosition(pos.x, pos.y))
        }
        None
    }
}

```

**Comment by eugene2k** [comment]
I don't see the problem, really. It may be convenient to have glutin implement a function to query the cursor position, but on some platforms it would have to implement the cursor tracking rather than provide a wrapper to an existing function. In other words it will be doing the same thing you are doing now, and it will be doing that regardless of whether your application needs this functionality or not, which, in my opinion isn't such a good thing.

**Comment by vberger** [comment]
Agreed.

Wayland is one such platform for example : there is no way for a wayland application to query the compositor, so the clients have to track the MouseMoved events no matter what.

**Comment by francesca64** [comment]
This should be closed, as 1) it's related to winit, and 2) we won't implement it.
