### ISSUE TITLE
Relative mouse motion

### ISSUE THREAD

**Issue by bvssvni** [tomaka/glutin#774]
This is needed for FPS games.

The old issue was [here](https://github.com/tomaka/glutin/issues/18), but closed because piston-input was considered.

**Comment by bvssvni** [comment]
From IRC:

> fkaa: bvssvni: just checked, deltaX/deltaY works when the mouse is grabbed (`CGAssociateMouseAndMouseCursorPosition(false)`)

**Comment by retep998** [comment]
From https://github.com/PistonDevelopers/hematite/issues/265

>For future reference of anyone who does decide to work on this you use RegisterRawInputDevices to register a device for raw input, and then you receive WM_INPUT messages through the normal message loop.

**Comment by LukasKalbertodt** [comment]
What is the status of this?

I'm a bit confused that this feature is not implemented in `glutin` yet. There are quite a few games using this library and quite a few of those need some kind of mouse grabbing with relative motion, I presume :wink: 

I know that this behavior can be simulated rather easy, but it's a bit of a hack. I also think that most OS-APIs can provide floating point relative movements (instead of being restricted to pixels).

So: any progress on this?

**Comment by Limeth** [comment]
Any updates on this? I am interested in a solution.
I currently use this piece of code, but as you may imagine, it's kind of buggy. The behavior is inconsistent across different platforms (tested on linux/windows). https://github.com/Limeth/euclider/blob/76bc8d4482bf5e84ef309b32efbdcb0ed7840f08/src/simulation.rs#L242

**Comment by bvssvni** [comment]
The glutin_window backend to Piston also works around this problem https://github.com/PistonDevelopers/glutin_window/blob/master/src/lib.rs#L216

**Comment by tomaka** [comment]
Closing for https://github.com/tomaka/winit/issues/70
