### ISSUE TITLE
Port glutin to winit

### ISSUE THREAD

**Issue by ozkriff** [tomaka/glutin#813]
In https://github.com/tomaka/glutin/issues/726#issuecomment-238913135 you said:

> The situation it's that it's painful but not difficult to switch glutin to winit and I don't have time and motivation to do that.

The situation/plans have not changed? I would like to try to help with this if you don't mind :)

**Comment by kvark** [comment]
GFX and Amethyst would very much benefit from this long-awaited change! cc @ebkalderon

**Comment by ebkalderon** [comment]
I agree with @kvark, having a windowing framework that isn't tied to any particular graphics API would be terrific!

**Comment by tomaka** [comment]
The things to do are basically:

- [ ] Merge glutin master in winit master. The git history is the same, but there have been PRs submitted to glutin after the fork and that haven't been merged.
- [ ] Remove win32 and x11 from `src/api`.
- [ ] Modify `android` and `wayland` in `src/api`  so that they just create an OpenGL context over a window passed by parameter, instead of creating the window themselves.
- [ ] Modify the files in `src/platform/*` (the content of these files are the layer right under the public API calls) to create a window from winit and an OpenGL context from one of the modules in `src/api`.

**Comment by kvark** [comment]
Thanks @tomaka ! This is a very nice task breakdown and the plan to follow.

**Comment by ozkriff** [comment]
Slowly working on draft for this in https://github.com/ozkriff/glutin/tree/omg branch.

Draft for linux/x11 works.

@Vinatorul is working on wayland backend.

**Comment by tomaka** [comment]
@ozkriff I'd like to highlight that:
> Add pub use statements in main.rs to reexport all the types that are in winit (ie. everything related to windowing).

The glutin user shouldn't have to add `winit` to their Cargo.toml in order to use glutin.

**Comment by vberger** [comment]
@ozkriff @Vinatorul Don't try too hard with the wayland backend, as said in an other issue, I'm going to completely rewrite the winit wayland backend following my complete redesign of tha wayland-client API with version 0.7, which will likely slightly change the wayland-EGL plumbing API (to make it more safe)

**Comment by tomaka** [comment]
@vberger There's a high chance that they finish the rework before you.

**Comment by ozkriff** [comment]
> The glutin user shouldn't have to add winit to their Cargo.toml in order to use glutin.

@tomaka Right now [zoc](https://github.com/ozkriff/zoc) works on linux/x11 without any changes if I add my forked glutin to .cargo/config :) .

By the way, what is the future of `ios` and `emscripten` backends? You haven't mentioned them in [plan](https://github.com/tomaka/glutin/issues/813#issuecomment-247071744).

**Comment by tomaka** [comment]
The `emscripten` can should stay as it is now, as there's no advantage in moving it to winit.
For iOS the problem is that we don't have anybody to test the changes. It's probably fine to leave it and add a "TODO: use winit as a backend".

If you add methods to convert between glutin and winit, just put `unimplemented!()` for these two targets.

**Comment by vberger** [comment]
Just to be more clear: with my previous message I didn't mean to consider my of the internals as blocking you. But if you reach a point where things get too messy with wayland on the old `wayland-client` API, just leave it as `unimplemented!()` and I'll correct it with the new backend afterwards.

**Comment by Vinatorul** [comment]
@vberger I have one idea to do it without hacks after conversation in winit issue. If it won't work - then I'll just wait for new API.

**Comment by ozkriff** [comment]
Android backend works. Moving to work on windows backend.

**Comment by ozkriff** [comment]
`cargo run --example window` works on windows. Started polishing code + trying to fix headless mode.

**Comment by sumproxy** [comment]
macOS backend now works too.

**Comment by ozkriff** [comment]
@tomaka I have a problem with Headless mode on win32:

I don't know how to get rid of `winit::Window` here:

https://github.com/ozkriff/glutin/blob/6ecf9e5/src/platform/windows/mod.rs#L136

because I need ` winapi::HWND` from it for context creation here:

https://github.com/ozkriff/glutin/blob/6ecf9e5/src/platform/windows/mod.rs#L136

**Comment by tomaka** [comment]
@ozkriff Well, you need to create a window yourself at this location.

**Comment by ozkriff** [comment]
Ok, seems like the only solution :( .

And, by the way, what should I do with `WindowAttributes` and `PlatformSpecificWindowBuilderAttributes` in glutin?

- Duplicate all `winit::WindowBuilder::with_*` functions in `glutin::WindowBuilder`? (convenient for user but might become a support nightmare)
- Let the user user create `winit::WIndow` himself and pass it to `glutin::WindowBuilder::with_window` or create default `wint::Window`? (DRY, but forces most of the users to use winit)

**Comment by tomaka** [comment]
> Ok, seems like the only solution :( .

It's the solution *by design*. Windows has nothing to create headless contexts (except an AMD-specific stuff) so we create a hidden window.

> Duplicate all winit::WindowBuilder::with_* functions in glutin::WindowBuilder? (convenient for user but might become a support nightmare)

This one.
By doing so we can add our own functions (for example allowing the user to choose between EGL and GLX), plus there may be situations in the future where want to deny access to some of the `winit::WindowBuilder::with_*` functions.

**Comment by ozkriff** [comment]
Done in https://github.com/tomaka/glutin/pull/819
