### ISSUE TITLE
window resize callback should accept closures

### ISSUE THREAD

**Issue by swiftcoder** [tomaka/glutin#859]
Currently, the window resize callback is a plain function pointer, which precludes the use of closures or instance methods.

This pretty much requires the use of static data to allow whatever callback you define to access instance data, which makes the library rather an unergonomic application of Rust.

Accepting closures would allow us to capture `self` and hence bind instance methods to the callback slot.

**Comment by tomaka** [comment]
That would be unsound unfortunately, because of leak safety (search for "thread scoped rust leakpocalypse" if you want to know more, it's a tought problem).

The resize callback is going to go away at some point: https://github.com/tomaka/winit/issues/20

**Comment by swiftcoder** [comment]
Fair. Event loops are likely the better way to solve this.

Is there any recommended workaround in the meantime?

**Comment by mitchmindtree** [comment]
@swiftcoder not other than using some sort of static data like you mention unfortunately. On the bright side, the issue that tomaka linked to has mostly been implemented upstream in tomaka/winit#126 and tomaka/winit#132, so it's mostly just a matter of waiting for the dust to settle so that winit can publish a new version, and then updating `glutin` to match the new `winit` API.

**Comment by francesca64** [comment]
Since resize callbacks no longer exist, this can be closed.
