### ISSUE TITLE
doesn't compile to arm-linux-androideabi

### ISSUE THREAD

**Issue by thiolliere** [tomaka/glutin#911]
error:
```
error[E0599]: no method named `resize` found for type `api::android::Context` in the current scope
   --> src/lib.rs:366:22
    |
366 |         self.context.resize(width, height);
    |                      ^^^^^^
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following trait defines an item `resize`, perhaps you need to implement it:
            candidate #1: `GlContext`

error: aborting due to previous error(s)

error: Could not compile `glutin`.
```

If you are OK I can implement an empty function resize for android Context

**Comment by cosier** [comment]
I have also run into this issue while building Conrod ui framework for Android.

Currently, I've put a path override in .cargo/config with a patched version of glutin with a empty *resize* fn on the Context impl. _Seems to work_.

However, since *resizing* is not applicable on mobile _(iOS context would also need this?)_, would it make more sense to do conditional branches on the GlContext impl instead of adding empty fn on both iOS and Android Contexts?

**Comment by ZeGentzy** [comment]
This has been fixed already. Closing.
