### ISSUE TITLE
glutin 0.9: "[wayland-client] Found library libwayland-client.so cannot be used.." message

### ISSUE THREAD

**Issue by ozkriff** [tomaka/glutin#920]
After the update to glutin v0.9.2 I'm getting this message to stdout on every app start:

```
$ ./target/debug/zemeroth
[wayland-client] Found library libwayland-client.so cannot be used: symbol wl_proxy_marshal_array_constructor_versioned is missing. 
```

**Comment by vberger** [comment]
This is a debug message from wayland-client, saying that it found a wayland installation on your system, but it is too old to be usable. As a result, winit will fallback to X11.

**Comment by ozkriff** [comment]
So it's working as intended? Can I disable this message somehow? Or what should I do?

**Comment by vberger** [comment]
This is a matter for wayland-rs, I've created an issue for it : https://github.com/Smithay/wayland-rs/issues/127

either this needs to be changed in wayland-client, or by updating your version of the wayland C libs, winit will be able to use them and will start in wayland mode

**Comment by ozkriff** [comment]
> updating your version of the wayland C libs

Btw, I have the latest libs for Kubuntu 16.04 LTS. Are they actually _that_ old? O.o

**Comment by vberger** [comment]
Well, the symbol wayland-sys is complaining about, `wl_proxy_marshal_array_constructor_versioned`, was introduced in wayland 1.10, released the 16th of February 2016.

It's not _that_ old, but it deprecates a previous mechanism, and I decided to only support the new one in wayland-client because the old one does not provide as much safety-guarantees as the new one. (putting aside that the machinery to detect which version of the wayland-libs is available and adapt the behavior of wayland-client accordingly would be quite boiler-plate-y)

**Comment by ZeGentzy** [comment]
Closing as wontfix.
